name: sklearn
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - joblib=0.14.1
  - jpeg=9c
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - parso=0.6.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.8.1
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11

